on:
  push:
    branches: [ master ]
name: Deploy website on push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "public_html"
        remoteDir: "public_html"
        options: "--exclude archive/ --delete --ignore-time --verbose=3"